server:
  port: 8001
  servlet:
    context-path: /payment
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #JPA相关配置
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
#mybatisplus配置
mybatis-plus:
  global-config:
    db-config:
      #配置mybatisplus的逻辑删除功能
      logic-delete-value: false  #默认删除的值
      logic-not-delete-value: true #默认未删除的值
      logic-delete-field: flag
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #在控制台输出调试信息

